### ISSUE TITLE
tracer object has no attribute start_active_span. using python lib

### ISSUE THREAD

**Issue by gane5hvarma** [jaegertracing/jaeger-client-python#244] opened 2019-03-25 14:20 UTC
As shown in the tutorial https://github.com/yurishkuro/opentracing-tutorial/tree/master/python/lesson02 . 
when i execute wiht tracer.start_span its working. but, using tracer.start_active_span is giving me an error saying tracer object has no attribute start_active_span

**Comment by gane5hvarma** [comment] 2019-03-27 06:27
@yurishkuro

**Comment by arwineap** [comment] 2019-04-04 18:13
@gane5hvarma I was having this issue, and noticed that I had opentracing version 1.3, but start_active_span was added in 2.0.0

https://github.com/opentracing/opentracing-python/commit/2f79bf319fb727da9ef451b4107179eb59e90eb8#diff-a1898244c8c6ea29725a1d5333973b9aR62

**Comment by arwineap** [comment] 2019-04-04 18:29
These actually seem to be the core of my issue after downgrading to 0.2.0

https://github.com/opentracing-contrib/python-flask/issues/29

https://github.com/jaegertracing/jaeger-client-python/issues/199

**Comment by yurishkuro** [comment] 2019-04-24 19:02
Duplicate of #199

**Closed by yurishkuro** 2019-04-24 19:02 UTC
