### ISSUE TITLE
class Tracer's bug 

### ISSUE THREAD

**Issue by zhanglianquan** [jaegertracing/jaeger-client-python#237] opened 2019-02-15 03:49 UTC
class Tracer(opentracing.Tracer):
    """
    N.B. metrics has been deprecated, use metrics_factory instead.
    """
    def __init__(
        self, service_name, reporter, sampler, metrics=None,
        metrics_factory=None,
        trace_id_header=constants.TRACE_ID_HEADER,
        baggage_header_prefix=constants.BAGGAGE_HEADER_PREFIX,
        debug_id_header=constants.DEBUG_ID_HEADER_KEY,
        one_span_per_rpc=False, extra_codecs=None,
        tags=None,
        max_tag_value_length=constants.MAX_TAG_VALUE_LENGTH,
        throttler=None,
    ):
       # Note: bug , can't implement super class opentracing.Tracer  's  scope_manager
        # super(Tracer, self).__init__()  
        self.service_name = service_name
        self.reporter = reporter
        self.sampler = sampler
        self.metrics_factory = metrics_factory or LegacyMetricsFactory(metrics or Metrics())
        self.metrics = TracerMetrics(self.metrics_factory)
        self.random = random.Random(time.time() * (os.getpid() or 1))
        self.debug_id_header = debug_id_header
        self.one_span_per_rpc = one_span_per_rpc
        self.max_tag_value_length = max_tag_value_length
        self.codecs = {
            Format.TEXT_MAP: TextCodec(
                url_encoding=False,
                trace_id_header=trace_id_header,
                baggage_header_prefix=baggage_header_prefix,
                debug_id_header=debug_id_header,
            ),
            Format.HTTP_HEADERS: TextCodec(
                url_encoding=True,
                trace_id_header=trace_id_header,
                baggage_header_prefix=baggage_header_prefix,
                debug_id_header=debug_id_header,
            ),
            Format.BINARY: BinaryCodec(),
            ZipkinSpanFormat: ZipkinCodec(),
        }
        if extra_codecs:
            self.codecs.update(extra_codecs)
        self.tags = {
            constants.JAEGER_VERSION_TAG_KEY: constants.JAEGER_CLIENT_VERSION,
        }
        if tags:
            self.tags.update(tags)

        if self.tags.get(constants.JAEGER_IP_TAG_KEY) is None:
            self.tags[constants.JAEGER_IP_TAG_KEY] = local_ip()

        if self.tags.get(constants.JAEGER_HOSTNAME_TAG_KEY) is None:
            try:
                hostname = socket.gethostname()
                self.tags[constants.JAEGER_HOSTNAME_TAG_KEY] = hostname
            except socket.error:
                logger.exception('Unable to determine host name')

        self.throttler = throttler
        if self.throttler:
            client_id = random.randint(0, sys.maxsize)
            self.throttler._set_client_id(client_id)
            self.tags[constants.CLIENT_UUID_TAG_KEY] = client_id

        self.reporter.set_process(
            service_name=self.service_name,
            tags=self.tags,
            max_length=self.max_tag_value_length,
        )

**Comment by zhanglianquan** [comment] 2019-02-15 03:49
# Note: bug , can't implement super class opentracing.Tracer  's  scope_manager
        # super(Tracer, self).__init__()

**Comment by pravarag** [comment] 2019-02-15 05:43
> # Note: bug , can't implement super class opentracing.Tracer 's scope_manager
> ```
>     # super(Tracer, self).__init__()  
> ```

did you face any particular error while implementing opentracing.Tracer's as super Class ?

**Comment by zhanglianquan** [comment] 2019-02-18 06:02
> > # Note: bug , can't implement super class opentracing.Tracer 's scope_manager
> > ```
> >     # super(Tracer, self).__init__()  
> > ```
> 
> did you face any particular error while implementing opentracing.Tracer as super Class ?


 # Handling done through a try construct:
       span = tracer.start_span(operation_name='someWork')
       scope = tracer.scope_manager.activate(span, True)
       try:
           # Do things.
       except Exception as e:
           scope.set_tag('error', '...')
       finally:
           scope.finish()

error tips：
AttributeError: 'Tracer' object has no attribute 'scope_manager'

**Comment by yurishkuro** [comment] 2019-02-18 15:36
Duplicate of #199

**Closed by yurishkuro** 2019-02-18 15:36 UTC
